defaultPlacement: end
enableVersioning: true
handle: footballs
name: footballs
propagationMethod: all
siteSettings:
  190887d5-cb25-4380-ba2c-ed78da8d1eaa: # Sportshop
    enabledByDefault: true
    hasUrls: true
    template: footballs/_entry
    uriFormat: 'footballs/{slug}'
type: channel
