defaultPlacement: end
enableVersioning: true
handle: footballshirts
name: footballshirts
propagationMethod: all
siteSettings:
  190887d5-cb25-4380-ba2c-ed78da8d1eaa: # Sportshop
    enabledByDefault: true
    hasUrls: true
    template: footballshirts/_entry
    uriFormat: 'footballshirts/{slug}'
type: channel
