fieldLayouts:
  b282b934-a823-4f87-87f4-b2e9eb34969a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 8ee6f5ec-da69-4e28-b9ca-f9e5cd72068a
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: a8318748-df77-4a39-a3f5-98bfdc6bfb6f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 88579ce1-9e0d-4e16-aedd-2b020d365624
        userCondition: null
fs: footballimages
handle: footballAssets
name: football-assets
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: footballimages
transformSubpath: ''
