fieldLayouts:
  58e27b99-a721-4c52-9835-60f61f77715c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8c84d48e-3270-451b-9ad3-20d4eb59fa6d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d71779fb-3aa4-4577-b652-96470138fbfa
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: da079aa4-9653-4d76-8894-c55498972928 # footballshoes
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
