fieldLayouts:
  ff4c4604-0bf3-4589-85ea-872a9dfe7c7b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 998d21d6-8826-4124-9b62-4ec72232314c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 99f3a95f-965d-4fd0-8e3e-d47c2d1ef2c3
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 1d05e0b2-7406-4efe-b25e-7a9daad960d8 # Homepage
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
