columnSuffix: null
contentColumnType: string
fieldGroup: 1ce5d3e8-a6a0-4bfc-9299-6220c3da2d51 # Common
handle: footballimage
instructions: null
name: footballImage
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultUploadLocationSource: 'volume:566e6c4a-96b2-4451-9282-77b881d066f0' # football-assets
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:566e6c4a-96b2-4451-9282-77b881d066f0' # football-assets
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
      -
        - conditionRules
        -
          -
            __assoc__:
              -
                - class
                - craft\elements\conditions\assets\FileSizeConditionRule
              -
                - uid
                - 771d63e8-4870-4548-b9d7-201471d0d8e9
              -
                - operator
                - '<'
              -
                - value
                - '100'
              -
                - maxValue
                - ''
              -
                - unit
                - MB
          -
            __assoc__:
              -
                - class
                - craft\elements\conditions\assets\WidthConditionRule
              -
                - uid
                - d6718075-b5ae-474e-b37b-5f584de056d7
              -
                - operator
                - '<='
              -
                - value
                - '500'
              -
                - maxValue
                - ''
          -
            __assoc__:
              -
                - class
                - craft\elements\conditions\assets\HeightConditionRule
              -
                - uid
                - 213a3d02-d257-44f4-b0a2-f39447f63336
              -
                - operator
                - '<='
              -
                - value
                - '500'
              -
                - maxValue
                - ''
  selectionLabel: null
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
