columnSuffix: vydvlsse
contentColumnType: string(20)
fieldGroup: 1ce5d3e8-a6a0-4bfc-9299-6220c3da2d51 # Common
handle: price
instructions: null
name: price
searchable: false
settings:
  byteLimit: null
  charLimit: 5
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
